version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building Lambda function code...
      - cd fetch_all
      - npm install
      - zip -r ../fetch-all-lambda-function.zip *
      - cd ..
      - zip -g fetch-all-lambda-function.zip appspec.yml
  post_build:
    commands:
      - echo Uploading Lambda function code to S3...
      - aws s3 cp fetch-all-lambda-function.zip s3://tech-ops-may23-bucket/
artifacts:
  files:
    - '**/*'
